In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_boston

In [19]:
data = pd.read_csv('train.csv')
data.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [20]:
data = data.set_index('PassengerId')
data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [21]:
data.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [22]:
target = 'Survived'

In [23]:
y = data[target]


In [24]:
x = data.drop(target, axis=1)
x.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Name      891 non-null    object 
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Ticket    891 non-null    object 
 7   Fare      891 non-null    float64
 8   Cabin     204 non-null    object 
 9   Embarked  889 non-null    object 
dtypes: float64(2), int64(3), object(5)
memory usage: 76.6+ KB


Не все поля полностью заполнены, удилаим лишние

In [25]:
x = x.drop(['Cabin', 'Name', 'Ticket'], axis=1)

In [29]:
mean_age = x['Age'].mean()
mean_age


29.699117647058763

In [27]:
x['Age'] = x['Age'].fillna(mean_age)

In [30]:
x['Age'].unique()

array([22.        , 38.        , 26.        , 35.        , 29.69911765,
       54.        ,  2.        , 27.        , 14.        ,  4.        ,
       58.        , 20.        , 39.        , 55.        , 31.        ,
       34.        , 15.        , 28.        ,  8.        , 19.        ,
       40.        , 66.        , 42.        , 21.        , 18.        ,
        3.        ,  7.        , 49.        , 29.        , 65.        ,
       28.5       ,  5.        , 11.        , 45.        , 17.        ,
       32.        , 16.        , 25.        ,  0.83      , 30.        ,
       33.        , 23.        , 24.        , 46.        , 59.        ,
       71.        , 37.        , 47.        , 14.5       , 70.5       ,
       32.5       , 12.        ,  9.        , 36.5       , 51.        ,
       55.5       , 40.5       , 44.        ,  1.        , 61.        ,
       56.        , 50.        , 36.        , 45.5       , 20.5       ,
       62.        , 41.        , 52.        , 63.        , 23.5 

в Embarked - не хватает 2х значений, но поле текстовое, заменим Модой

In [32]:
x['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [36]:
embarked_mode = x['Embarked'].mode()[0]
embarked_mode

'S'

In [37]:
x['Embarked'] = x['Embarked'].fillna(embarked_mode)
x['Embarked'].value_counts()

S    646
C    168
Q     77
Name: Embarked, dtype: int64

In [38]:
x.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Sex       891 non-null    object 
 2   Age       891 non-null    float64
 3   SibSp     891 non-null    int64  
 4   Parch     891 non-null    int64  
 5   Fare      891 non-null    float64
 6   Embarked  891 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 55.7+ KB


Преобразуем категории в цифровой вид:

In [39]:
x['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [40]:
x['Sex'] = (x['Sex'] == 'female').astype(int)

In [41]:
x['Sex'].value_counts()

0    577
1    314
Name: Sex, dtype: int64

теперь Embarked
Преобразуем ее в dummy-переменные
Теперь каждому ее значению будет отведен отдельный столбец
в котором возможны два числа:
    1 (переменная равна данному значению)
    0 (переменная не равна данному значению)

In [43]:
x = pd.get_dummies(x)

In [44]:
x.columns

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked_C',
       'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [45]:
x.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  \
PassengerId                                                                     
1                 3    0  22.0      1      0   7.2500           0           0   
2                 1    1  38.0      1      0  71.2833           1           0   
3                 3    1  26.0      0      0   7.9250           0           0   
4                 1    1  35.0      1      0  53.1000           0           0   
5                 3    0  35.0      0      0   8.0500           0           0   

             Embarked_S  
PassengerId              
1                     1  
2                     0  
3                     1  
4                     1  
5                     1

In [47]:
x['Pclass'].unique()

array([3, 1, 2], dtype=int64)

In [48]:
x['Pclass'] = x['Pclass'].astype('category')

In [49]:
x = pd.get_dummies(x)
x.columns

Index(['Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked_C', 'Embarked_Q',
       'Embarked_S', 'Pclass_1', 'Pclass_2', 'Pclass_3'],
      dtype='object')

In [50]:
x.head(10)

Sex        Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  \
PassengerId                                                                  
1              0  22.000000      1      0   7.2500           0           0   
2              1  38.000000      1      0  71.2833           1           0   
3              1  26.000000      0      0   7.9250           0           0   
4              1  35.000000      1      0  53.1000           0           0   
5              0  35.000000      0      0   8.0500           0           0   
6              0  29.699118      0      0   8.4583           0           1   
7              0  54.000000      0      0  51.8625           0           0   
8              0   2.000000      3      1  21.0750           0           0   
9              1  27.000000      0      2  11.1333           0           0   
10             1  14.000000      1      0  30.0708           1           0   

             Embarked_S  Pclass_1  Pclass_2  Pclass_3  
PassengerId                                            
1                     1         0         0         1  
2                     0         1         0         0  
3                     1         0         0         1  
4                     1         1         0         0  
5                     1         0         0         1  
6                     0         0         0         1  
7                     1         1         0         0  
8                     1         0         0         1  
9                     1         0         0         1  
10                    0         0         1         0

In [51]:
# Парамерт test_size будет определять, какую долю данных
# из train.csv берем для валидации датасета
from sklearn.model_selection import train_test_split

x_train, x_valid, y_train, y_valid = train_test_split(x, y, test_size=0.25, random_state=42)

In [52]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 668 entries, 299 to 103
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Sex         668 non-null    int32  
 1   Age         668 non-null    float64
 2   SibSp       668 non-null    int64  
 3   Parch       668 non-null    int64  
 4   Fare        668 non-null    float64
 5   Embarked_C  668 non-null    uint8  
 6   Embarked_Q  668 non-null    uint8  
 7   Embarked_S  668 non-null    uint8  
 8   Pclass_1    668 non-null    uint8  
 9   Pclass_2    668 non-null    uint8  
 10  Pclass_3    668 non-null    uint8  
dtypes: float64(2), int32(1), int64(2), uint8(6)
memory usage: 32.6 KB


In [55]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()


In [56]:
lr.fit(x_train, y_train)

LogisticRegression()

In [58]:
y_pred = lr.predict(x_valid)
y_pred

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0], dtype=int64)

Метрика Accuracy (доля правильных ответов)

In [60]:
from sklearn.metrics import accuracy_score

In [61]:
accuracy_score(y_valid, y_pred)

0.8026905829596412

In [62]:
y_pred_train = lr.predict(x_train)

In [64]:
accuracy_score(y_train, y_pred_train)

0.8083832335329342

## Вычисление вероятных событий

In [65]:
y_proba = lr.predict_proba(x_valid)

In [67]:
# Вероятность событий 0 и 1 для каждого пассажира
y_proba

array([[0.88803846, 0.11196154],
       [0.7306994 , 0.2693006 ],
       [0.87015653, 0.12984347],
       [0.08991938, 0.91008062],
       [0.25062018, 0.74937982],
       [0.07826309, 0.92173691],
       [0.3344696 , 0.6655304 ],
       [0.90522441, 0.09477559],
       [0.24542479, 0.75457521],
       [0.10340604, 0.89659396],
       [0.69433675, 0.30566325],
       [0.93487211, 0.06512789],
       [0.62484703, 0.37515297],
       [0.8476136 , 0.1523864 ],
       [0.75859307, 0.24140693],
       [0.07898048, 0.92101952],
       [0.72748704, 0.27251296],
       [0.33438493, 0.66561507],
       [0.70247547, 0.29752453],
       [0.70651161, 0.29348839],
       [0.88386346, 0.11613654],
       [0.6428651 , 0.3571349 ],
       [0.39821924, 0.60178076],
       [0.86944941, 0.13055059],
       [0.89833287, 0.10166713],
       [0.92821101, 0.07178899],
       [0.56597441, 0.43402559],
       [0.72832999, 0.27167001],
       [0.9144287 , 0.0855713 ],
       [0.42638413, 0.57361587],
       [0.

Нас интересует вероятность собития 1 (правый столбец) -
при получении ответа значения из него округляются до 0 или до 1

## Сохранение данных
сохраним обработанные данные, они пригодятся для следующих уроков

In [68]:
x_train.to_pickle('x_train.pkl')
y_train.to_pickle('y_train.pkl')

x_valid.to_pickle('x_valid.pkl')
y_valid.to_pickle('y_valid.pkl')